'''
The code that performs the actual simulation.
'''

# simulation defaults
DEFAULT_SIMULATION_DAYS = 211
DEFAULT_POPULATION = 50000
DEFAULT_INITIAL_INFECTION = 20
# define the keys for the simulation state
# some of the basic stuff
SIMULATION_DAYS = 'simulation_days'
POPULATION = 'population'
INITIAL_INFECTION = 'initial_infection'
PEOPLE = 'people'
HEALTH_STATES = 'health_states'
PHASES = 'phases'

# Properties for the simulation of the current day
CURRENT_PHASE = 'current_phase'
HAS_NEXT_PHASE = 'has_next_phase'
CURRENT_DAILY_CONTACTS = 'current_daily_contacts'
CURRENT_TRANSMISSION_PROBABILITY = 'current_transmission_probability'

# There are days when the maximum of something happens.
MAX_NEW_DAILY_CASES = 'max_new_daily_cases_day'
MAX_NEW_DAILY_DIAGNOSED_CASES = 'max_new_daily_diagnosed_cases_day'
MAX_ACTIVE_CASES = 'max_active_cases_day'
MAX_ACTIVE_DIAGNOSED_CASES = 'max_active_diagnosed_cases_day'
MAX_ACTIVE_HOSPITALIZATIONS = 'max_active_hospitalizations_day'

# The series data being generated by the simulation
CUMULATIVE_CASES_SERIES = 'cumulative_cases_series'
CUMULATIVE_DIAGNOSED_CASES_SERIES = 'cumulative_diagnosed_cases_series'
CUMULATIVE_HOSPITALIZATIONS_SERIES = 'cumulative_hospitalizations_series'
CUMULATIVE_RECOVERIES_SERIES = 'cumulative_recoveries_series'
CUMULATIVE_DEATHS_SERIES = 'cumulative_deaths_series'
ACTIVE_CASES_SERIES = 'active_cases_series'
ACTIVE_DIAGNOSED_CASES_SERIES = 'active_diagnosed_cases_series'
ACTIVE_HOSPITALIZED_CASES_SERIES = 'active_hospitalized_cases_series'
NEW_CASES_SERIES = 'new_cases_series'
NEW_DIAGNOSED_CASES_SERIES = 'new_diagnosed_cases_series'
NEW_ACTIVE_CASES_SERIES = 'new_active_cases_series'
NEW_HOSPITALIZED_SERIES = 'new_hospitalized_cases_series'
NEW_RECOVERIES_SERIES = 'new_recoveries_series'
NEW_DEATHS_SERIES = 'new_deaths_series'


# The parameters for today

def create_initial_state(health_states, phases,
                         simulation_days=DEFAULT_SIMULATION_DAYS,
                         population=DEFAULT_POPULATION,
                         initial_infection=DEFAULT_INITIAL_INFECTION):
    sim_state = {
        SIMULATION_DAYS: simulation_days,
        POPULATION: population,
        INITIAL_INFECTION: initial_infection,
        PEOPLE: [],
        HEALTH_STATES: health_states,
        PHASES: phases,
        MAX_NEW_DAILY_CASES: 0,
        MAX_NEW_DAILY_DIAGNOSED_CASES: 0,
        MAX_ACTIVE_CASES: 0,
        MAX_ACTIVE_DIAGNOSED_CASES: 0,
        MAX_ACTIVE_HOSPITALIZATIONS: 0,
        CUMULATIVE_CASES_SERIES: [initial_infection],
        CUMULATIVE_DIAGNOSED_CASES_SERIES: [0],
        CUMULATIVE_HOSPITALIZATIONS_SERIES: [0],
        CUMULATIVE_RECOVERIES_SERIES: [0],
        CUMULATIVE_DEATHS_SERIES: [0],
        ACTIVE_CASES_SERIES: [initial_infection],
        ACTIVE_DIAGNOSED_CASES_SERIES: [0],
        ACTIVE_HOSPITALIZED_CASES_SERIES: [0],
        NEW_CASES_SERIES: [0],
        NEW_DIAGNOSED_CASES_SERIES: [0],
        NEW_ACTIVE_CASES_SERIES: [0],
        NEW_HOSPITALIZED_SERIES: [0],
        NEW_RECOVERIES_SERIES: [0],
        NEW_DEATHS_SERIES: [0]
    }
    return sim_state
